name: xxxx

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

  wait-for-approval:
    needs: build
    runs-on: ubuntu-latest
    environment: 'production'
    steps:
      - name: Waiting for approval
        run: echo "Approved by administrator"


  publish:
    needs: wait-for-approval
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest

  deploy:
    needs: publish
    runs-on: self-hosted && office-win11
    steps:
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Pull latest image
        run: docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
        
      - name: Stop existing container
        run: |
          docker stop spring-app || true
          docker rm spring-app || true
        continue-on-error: true
        
      - name: Run new container
        run: |
          docker run -d --name spring-app -p 8080:8989 ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest